fix: char can be signed or unsigned depending on platform, make it explicit
chars can be signed or unsigned by default, as we expect signed here, make it
explicit.

Fixes error on arm64:

./../vtools/dialogs/tools/dialogtool.h:100:45: error: enumerator value ‘-7’ is outside the range of underlying type ‘char’
  100 | enum class DialogPosition : char {Offset = -7, BottomRight, BottomLeft, Center, TopRight, TopLeft};
      |